SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID  FROM EMPLOYEES;

-- find employees full name with their manager's
SELECT *
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID;

SELECT E2.FIRST_NAME, E2.LAST_NAME, E1.FIRST_NAME
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
 ON E1.EMPLOYEE_ID = E2.MANAGER_ID;