SELECT * FROM EMPLOYEES;

/*
    CREATE VIEW
 */

CREATE VIEW SDET AS
SELECT (SUBSTR(FIRST_NAME, 0, 1) || SUBSTR(LAST_NAME, 0, 1)) AS INITIALS,
       (FIRST_NAME || ' makes $' || SALARY) AS EMPLOYEES_SALARY
FROM EMPLOYEES;

SELECT * FROM SDET;
SELECT INITIALS FROm SDET;
SELECT EMPLOYEES_SALARY FROM SDET;

--SELECT EMPLOYEES_SALARY FROM SDET2;


-- How we can remove the VIEWS we created
DROP VIEW SDET;
--DROP VIEW SDET2;