SELECT * FROM EMPLOYEES;

-- get me how many different departments we have for each location_id
SELECT * FROM DEPARTMENTS;
SELECT COUNT (*) FROM DEPARTMENTS;

SELECT LOCATION_ID FROM DEPARTMENTS;
SELECT COUNT (LOCATION_ID) FROM DEPARTMENTS;


SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS;
--OR
SELECT LOCATION_ID FROM DEPARTMENTS
GROUP BY LOCATION_ID;

SELECT LOCATION_ID, COUNT(*) FROM DEPARTMENTS
GROUP BY LOCATION_ID;


-- get me how many locations we have for each country_id
SELECT * FROM LOCATIONS;

SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY COUNTRY_ID DESC; -- ASC is default


-- get me how many countries we have for each region (countries)
SELECT * FROM COUNTRIES;

SELECT REGION_ID, COUNT(*) FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY COUNT(*) DESC;

-- OR
SELECT REGION_ID, COUNT(*) AS "TOTAL NUMBER FOR EACH RI" FROM COUNTRIES -- with AS we renamed out column COUNT(*) as the one we want
GROUP BY REGION_ID
ORDER BY "TOTAL NUMBER FOR EACH RI" DESC;