--In works like "or logic"

SELECT * FROM Employees;


SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' or JOB_ID = 'SA_REP';


--We can write the same with in clause
SELECT * FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'SA_REP');

SELECT city, COUNTRY_ID FROM LOCATIONS;

SELECT CITY, COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID IN ('IT', 'US', 'UK');


SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(123, 134, 145, 146);



--get those which are not equal to IT_PROG and SA_REP
SELECT * FROM EMPLOYEES
WHERE JOB_ID NOT IN('IT_PROG', 'SA_REP');


SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;


SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;